crm/app1/urls.py
from django.urls import path
from app1 import views
app_name='app1'
urlpatterns = [
    path("",views.index,name='index'),
    path("home",views.Homepg.as_view(),name='home'),
    path("addcourse",views.reg,name='course'),
    path("edit/<int:pk>",views.edit,name='edit'),
    path("delete/<int:pk>",views.delete,name='delete'),
    path("editb/<int:pk>",views.editb,name='editb'),
    path("deleteb/<int:pk>",views.deleteb,name='deleteb'),
    path("addbatch",views.batchreg,name='batch'),
    path("register",views.newuser,name='newusr'),
    path("adm", views.admin, name='admin'),
    path("hr", views.hr, name='hr'),
    path("vcourse",views.vcourse,name='vcourse'),
    path("vbatch/<str:pk>",views.vbatch,name='vbatch'),
    path("vstu/<str:pk>", views.vstudent, name='vstu'),
    path("details/<str:pk>", views.studetails, name='details'),
    path("allstu", views.allstu, name='allstu'),
    path('ajax/getdrop',views.get_batch,name='getdrop'),
    path("search",views.search,name='search'),
    path("studentpg", views.Stupg, name='stupg'),
    path("registerhr",views.RegisterHR.as_view(),name='regHR'),
    path("approvetmtable",views.ViewTimeTable.as_view(),name='verifytm'),
    path("verifiedtables",views.aptimetable,name='aptb'),
    path("studentViewTb",views.VTimeTable.as_view(),name='stutb'),
    path("addtrainer",views.AddTrainer.as_view(),name='addtra'),
    path("addpayment",views.Addpayment.as_view(),name='addpay'),
    path("viewtrainer", views.ViewTrainer.as_view(), name='viewtra'),
    path("trainerpg",views.TrainerPg,name='trapg'),
    path("viewdailysessionreport/<int:pk>", views.vdailysession, name='vdsp'),

]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("app1.urls")),
    path("timetable", include("timetable.urls")),
    path("dailysessionreport", include("dsp.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
]

crm/dsp/urls.py
from django.urls import path
from dsp import views
app_name='dsp'
urlpatterns = [
    path("create/<str:pk>",views.DailyReport,name='report'),
    path("details/<int:pk>",views.Detail.as_view(),name='details'),
]

crm/timetable/urls.py
from django.urls import path
from timetable import views
app_name='timetable'
urlpatterns = [
    path("createt",views.CreateTable,name='create'),
    path("ajax/getdrop",views.get_room,name='getdrop'),
    path("timetable",views.ViewTimeTable.as_view(),name='view'),
    path("form",views.get_form,name='form'),
    path("endsession",views.endsession,name='end'),
    path("toapprovetb",views.toapprovetimetable,name='toapprove'),
]

crm/app1/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
class Course(models.Model):
    Course_Name=models.CharField(max_length=150,unique=True)

    def __str__(self):
        return self.Course_Name

class Batch(models.Model):
    Select_Course=models.ForeignKey(Course,on_delete=models.CASCADE)
    Batch_Code=models.CharField(max_length=150,unique=True)
    Active_Status=models.IntegerField(default=1)
    Date=models.DateField()
    Fees=models.CharField(max_length=190)
    def __str__(self):
        return self.Batch_Code
class Trainer(models.Model):
    Name=models.CharField(max_length=250,unique=True)
    Phone_No = models.CharField(max_length=10)
    Email = models.EmailField()
    Verify_Email = models.EmailField()
    Password = models.CharField(max_length=150)
    def __str__(self):
        return self.Name
from timetable.models import ClassRoom
class User(models.Model):
    User_Email=models.EmailField(unique=True)
    Password=models.CharField(max_length=150)
    def __str__(self):
        return self.User_Email

class Payment(models.Model):
    Type=models.CharField(max_length=200,unique=True)
    def __str__(self):
        return self.Type

class Register(models.Model):
    Name=models.CharField(max_length=150)
    Qualification=models.CharField(max_length=250)
    Address=models.TextField()
    Phone_No=models.CharField(max_length=10)
    Email=models.EmailField()
    Verify_Email=models.EmailField()
    Password=models.CharField(max_length=150)
    Select_Course=models.ForeignKey(Course,on_delete=models.CASCADE)
    Select_Batch=models.ForeignKey(Batch,on_delete=models.CASCADE)
    Payment=models.ForeignKey(Payment,on_delete=models.CASCADE)
    def __str__(self):
        return self.Name
class HrUser(models.Model):
    Name = models.CharField(max_length=150)
    Phone_No = models.CharField(max_length=10)
    Email = models.EmailField()
    Verify_Email = models.EmailField()
    Password = models.CharField(max_length=150)

class ApprovedTable(models.Model):
    Select_Batch=models.ForeignKey(Batch,on_delete=models.CASCADE)
    Start_Time = models.TimeField()
    End_Time = models.TimeField()
    Class_Room=models.ForeignKey(ClassRoom,on_delete=models.CASCADE)
    Date=models.DateField()
    def __str__(self):
        return str(self.Date)

crm/app1/forms.py
from app1.models import Course,Batch,User,Register
from django import forms
class RegCourse(forms.ModelForm):
    class Meta:
        model=Course
        fields='__all__'
class RegBatch(forms.ModelForm):
    class Meta:
        model=Batch
        fields='__all__'
class RegUser(forms.ModelForm):
    class Meta:
        model=User
        fields='__all__'
class NewUser(forms.ModelForm):
    class Meta:
        model=Register
        fields='__all__'
        labels = {
            'Name':'FullName',
            'Qualification':'Qualifications',
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['Select_Batch'].queryset=Batch.objects.none()

    def clean(self):
        all_clean_data = super(NewUser,self).clean()
        print(all_clean_data)
        email = all_clean_data["Email"]
        vmail = all_clean_data["Verify_Email"]
        print(email, vmail)
        if email != vmail:
            print("inside if")
            raise forms.ValidationError("MAKE SURE EMAILS MATCH")
        return all_clean_data

crm/app1/views.py
from django.shortcuts import render,get_object_or_404
from app1.forms import RegCourse,RegBatch,RegUser,NewUser
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from app1.models import Course,Batch,Register,User,HrUser,ApprovedTable,Trainer,Payment
from django.views.generic import CreateView,TemplateView,ListView
from dsp.models import SessionReport
from timetable.models import ToApproveTB
# Create your views here.
def index(request):
    return render(request,"app1/index.html")

def reg(request):
    obj=RegCourse()
    cr=Course.objects.all()
    dict={"reg":obj,"cr":cr}
    if request.method=='POST':
        frm=RegCourse(request.POST)
        if frm.is_valid():
            frm.save(commit=True)
    return render(request,"app1/addcourse.html",dict)
def edit(request,pk):
    obj=get_object_or_404(Course,pk=pk)
    frm=RegCourse(instance=obj)
    dict={"frm":frm}
    if(request.method=='POST'):
        fm=RegCourse(request.POST)
        if fm.is_valid():
            up=fm.cleaned_data["Course_Name"]
            obj.Course_Name=up
            obj.save()
            return reg(request)
    return render(request,"app1/edit.html",dict)

def delete(request,pk):
    obj=get_object_or_404(Course,pk=pk)
    dict={"obj":obj}
    if(request.method=='POST'):
        obj.delete()
        return reg(request)
    return render(request,"app1/delete.html",dict)
def batchreg(request):
    obj=RegBatch()
    ba=Batch.objects.all()
    dict={"obj":obj,"ba":ba}
    if request.method=='POST':
        rec=RegBatch(request.POST)
        if rec.is_valid():
            rec.save(commit=True)
    return render(request,"app1/addbatch.html",dict)
def editb(request,pk):
    obj=get_object_or_404(Batch, pk=pk)
    frm=RegBatch(instance=obj)
    dict={"frm": frm}
    if (request.method == 'POST'):
        fm=RegBatch(request.POST)
        if fm.is_valid():
            bc=fm.cleaned_data["Batch_Code"]
            sc=fm.cleaned_data["Select_Course"]
            d=fm.cleaned_data["Date"]
            fe=fm.cleaned_data["Fees"]
            obj.Batch_Code=bc
            obj.Select_Course=sc
            obj.Date=d
            obj.Fees=fe
            obj.save()
            return batchreg(request)
    return render(request,"app1/editb.html",dict)

def deleteb(request,pk):
    obj=get_object_or_404(Batch,pk=pk)
    dict={"obj":obj}
    if (request.method == 'POST'):
        obj.delete()
        return batchreg(request)
    return render(request,"app1/deleteb.html",dict)
def get_batch(request):
    course=request.GET.get('Select_Course')
    batch = Batch.objects.filter(Select_Course_id=course)
    return render(request,'app1/getdrop.html', {'batch': batch})
def newuser(request):
    obj=NewUser()
    dict1={"nusr":obj}
    if request.method=='POST':
        mydit=dict(request.POST)
        print(mydit)
        print(mydit["Name"][0])
        co=Course.objects.get(pk=mydit["Select_Course"][0])
        ba=Batch.objects.get(pk=mydit["Select_Batch"][0])
        pa=Payment.objects.get(pk=mydit["Payment"][0])
        em=mydit["Email"][0]
        vm=mydit["Verify_Email"][0]
        if(em==vm):
            nus=Register(Name=mydit["Name"][0],Qualification=mydit["Qualification"][0],Address=mydit["Address"][0],Phone_No=mydit["Phone_No"][0],Email=mydit["Email"][0],Verify_Email=mydit["Verify_Email"][0],Password=mydit["Password"][0],Select_Course=co,Select_Batch=ba,Payment=pa)
            nus.save()
        else:
            raise ValidationError("Error Emails Do not Match")
    return render(request,"app1/register.html",dict1)
def admin(request):
    return render(request,"app1/admin.html")
class RegisterHR(CreateView):
    model = HrUser
    fields = '__all__'
    template_name = 'app1/registerhr.html'
    success_url = reverse_lazy('app1:admin')
def hr(request):
    form = RegUser()
    dict = {'form': form}
    us =HrUser.objects.all()
    if request.method == 'POST':
        frm = RegUser(request.POST)
        if frm.is_valid():
            em = frm.cleaned_data['User_Email']
            pa = frm.cleaned_data['Password']
            for i in us:
                if (i.Email == em and i.Password == pa):
                    dict = {'stu': i}
                    return render(request, "app1/hr.html", dict)
    return render(request,"app1/hr.html",dict)
def vcourse(request):
    obj=Course.objects.all()
    dict={"obj":obj}
    return render(request,"app1/courses.html",dict)
def vbatch(request,pk):
    co=Course.objects.get(Course_Name=pk)
    obj=Batch.objects.filter(Select_Course=co)
    dict={"rec":obj}
    return render(request,"app1/batches.html",dict)
def vstudent(request,pk):
    ba=Batch.objects.get(Batch_Code=pk)
    obj=Register.objects.filter(Select_Batch=ba)
    dict={"rec":obj}
    return render(request,"app1/students.html",dict)
def studetails(request,pk):
    obj=Register.objects.get(Name=pk)
    dict = {"rec": obj}
    return render(request, "app1/userpg.html", dict)
def allstu(request):
    obj=Register.objects.all()
    dict = {"rec": obj}
    return render(request, "app1/students.html", dict)
def search(request):
    if request.method=='GET':
        pk=request.GET.get('q')
        result=Register.objects.filter(Q(Name__icontains=pk) |Q(Qualification__icontains=pk) |Q(Email__icontains=pk) |Q(Address__icontains=pk))
        if result.exists():
            dict={"records":result}
            return render(request,"app1/searchpg.html",dict)
        else:
            result=Batch.objects.filter(Q(Batch_Code__icontains=pk) |Q(Date__icontains=pk))
            if result.exists():
                dict={"rec":result}
                return render(request,"app1/batches.html",dict)
            else:
                result=Course.objects.filter(Q(Course_Name__icontains=pk))
                if result.exists():
                    dict={"obj":result}
                    return render(request,"app1/courses.html",dict)
                else:
                    return index(request)
    return render(request,"app1/base.html")
class Homepg(TemplateView):
    template_name = 'registration/home.html'
def Stupg(request):
    form=RegUser()
    dict={'form':form}
    us=Register.objects.all()
    if request.method=='POST':
        frm=RegUser(request.POST)
        if frm.is_valid():
            em=frm.cleaned_data['User_Email']
            pa=frm.cleaned_data['Password']
            for i in us:
                if(i.Email==em and i.Password==pa):
                    dict={'stu':i}
                    return render(request,"app1/studentpg.html",dict)
    return render(request,"app1/studentpg.html",dict)
class ViewTimeTable(ListView):
    model = ToApproveTB
    context_object_name = 'records'
    template_name = 'app1/timetable.html'
def aptimetable(request):
    tb=ToApproveTB.objects.all()
    ob = ApprovedTable.objects.all()
    ob.delete()
    for i in tb:
        obj=ApprovedTable(Select_Batch=i.Select_Batch,Start_Time=i.Start_Time,End_Time=i.End_Time,Class_Room=i.Class_Room,Date=i.Date)
        obj.save()
    return admin(request)
class VTimeTable(ListView):
    model = ApprovedTable
    context_object_name = 'records'
    template_name = 'app1/viewtimetable.html'
class AddTrainer(CreateView):
    model = Trainer
    fields = '__all__'
    template_name = 'app1/addtrainer.html'
    success_url = reverse_lazy('app1:admin')
class Addpayment(CreateView):
    model = Payment
    fields = '__all__'
    template_name = 'app1/payment.html'
    success_url = reverse_lazy('app1:hr')
class ViewTrainer(ListView):
    model = Trainer
    context_object_name = 'records'
    template_name = 'app1/viewtrainer.html'
def TrainerPg(request):
    form = RegUser()
    dict = {'form': form}
    us =Trainer.objects.all()
    if request.method == 'POST':
        frm = RegUser(request.POST)
        if frm.is_valid():
            em = frm.cleaned_data['User_Email']
            pa = frm.cleaned_data['Password']
            for i in us:
                if (i.Email == em and i.Password == pa):
                    dict = {'stu': i}
                    return render(request, "app1/trainer.html", dict)
    return render(request,"app1/trainer.html",dict)
def vdailysession(request,pk):
    obj=Trainer.objects.get(pk=pk)
    dsp=SessionReport.objects.filter(Trainer_Name=obj)
    print(dsp)
    dict={"records":dsp}
    return render(request,"app1/dailysessionreports.html",dict)

crm/app1/templates/app1/addbatch.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
    {% block body_block%}
    <title>ADD BATCH</title>

<style>
.ex1 {
  margin-bottom: 25px;
  color:grey;
  font-weight:bold;
}
</style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<div class="jumbotron">
    <blockquote class="blockquote text-center">
<h1 class="ex1">BATCH DETAILS</h1>
    </blockquote>
    <form method="post">
        {% csrf_token%}
        {{obj.as_p}}
        <input type="submit" value="Submit">
    </form>
    <div class="container"style="margin top">
        <table class="table">
            <thead>
    <tr>
      <th scope="col">BATCH CODE</th>
      <th scope="col">COURSE</th>
      <th scope="col">DATE</th>
    </tr>
  </thead>
            <tbody>
            {%for rec in ba%}
            <tr scope="row">
                <td>{{rec}}</td>
                <td>{{rec.Select_Course}}</td>
                <td>{{rec.Date}}</td>
                <td>{{rec.Fees}}</td>
                <td><a class="btn btn-success" href="{%url 'app1:editb' rec.id%}" role="button">EDIT</a></td>
                <td><a class="btn btn-danger" href="{% url 'app1:deleteb' rec.id%}" role="button">DELETE</a></td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
    </div>
</div>
{%endblock%}

crm/app1/templates/app1/addtrainer.html
<!DOCTYPE html>
{%extends 'app1/base.html'%}
{%block body_block%}
   <div class="jumbotron">
        <form method="post">
            {%csrf_token%}
            {{form.as_p}}
            <input class="btn btn-success" type="submit" value="Submit">
        </form>
    </div>
{%endblock%}

crm/app1/templates/app1/admin.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
    {% block body_block%}
    <title>ADMIN</title>
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">ADMIN</a>
  <a href="{%url 'app1:course'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">add_box</i>ADD COURSE</a>
  <a href="{%url 'app1:batch'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">add_box</i>ADD BATCH</a>
  <a href="{%url 'app1:addtra'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">add_box</i>ADD TRAINER</a>
    <a href="{%url 'app1:regHR'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">add_box</i>REGISTER HR</a>
    <a href="{%url 'app1:verifytm'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">verified_user</i>VERIFY TIMETABLE</a>
</div>
{%endblock%}

crm/app1/templates/app1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div class="col-lg-12">
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark" style="margin-left:-20px;margin-right:-15px;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'app1:index'%}" style="font-weight:bold;">HOME</a>
        {%if user.is_authenticated%}
        <a class="nav-item nav-link" href="{% url 'app1:admin'%}" style="font-weight:bold;">ADMIN</a>
        <a class="nav-item nav-link" href="{%url 'app1:hr'%}" style="font-weight:bold;">HR</a>
        <a class="nav-item nav-link" href="{%url 'app1:viewtra'%}" style="font-weight:bold;">TRAINER</a>
        <a class="nav-item nav-link" href="{%url 'app1:stupg'%}" style="font-weight:bold;">STUDENT</a>
          </div>
  </div>
        <form class="form-inline" style="float:right;" method="get" action="{%url 'app1:search'%}">
        <input class="form-control mr-sm-2" type="text" name="q" value="{{request.GET.q}}" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <h5 class="text-muted mr-sm-2" style="margin:6px;">Logged in as {{user.username}}</h5>
    <a class="btn btn-danger mr-sm-2" href="{%url 'logout'%}" role="button">Log Out</a>
    {%endif%}
</nav>
</div>
<div class="container-fluid">
    {% block body_block%}



    {%endblock%}
</div>
</body>
</html>

crm/app1/templates/app1/dailysessionreports.html
<!DOCTYPE html>
{%extends 'app1/base.html'%}
{%block body_block%}
    <title>Details</title>
<div class="jumbotron">
    {%for rec in records%}
    <button type="button" class="btn btn-dark btn-lg" style="margin:5px;">{{rec.Trainer_Name}}</button>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">DATE</th>
      <th scope="col">STUDENT</th>
      <th scope="col">TOPIC</th>
      <th scope="col">STATUS</th>
      <th scope="col">FEEDBACK</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <td scope="col">{{rec}}</td>
      <td scope="col">{{rec.Student_Name}}</td>
      <td scope="col">{{rec.Topic}}</td>
      <td scope="col">{{rec.Status}}</td>
      <td scope="col">{{rec.FeedBack}}</td>
    </tr>
  </tbody>
</table>
    {%endfor%}
    </div>
{%endblock%}

crm/app1/templates/app1/delete.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
    {% block body_block%}
    <title>DELETE</title>
<div class="jumbotron">
    <form method="post">
        {%csrf_token%}
        <h1>Are You Sure You Want to Delete?</h1>
        <h2>Course:{{obj}}</h2>
        <input class="btn btn-success" type="submit" value="Submit" >
    </form>
</div>
{%endblock%}

crm/app1/templates/app1/deleteb.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
    {% block body_block%}
    <title>DELETE BATCH</title>
<div class="jumbotron">
    <form method="post">
        {%csrf_token%}
        <h1>Are You Sure You Want to Delete?</h1>
        <h2>Batch:{{obj}}</h2>
        <input class="btn btn-success" type="submit" value="Submit" >
    </form>
</div>
{%endblock%}

crm/app1/templates/app1/getdrop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get Drop</title>
</head>
<body>
<option value="">---------</option>
{% for i in batch %}
<option value="{{ i.pk }}">{{ i.Batch_Code }}</option>
{% endfor %}
</body>
</html>

crm/app1/templates/app1/hr.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
{%load staticfiles%}
    {% block body_block%}
{%if user.is_authenticated%}
 <a href="{%url 'app1:newusr'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">how_to_reg</i>STUDENT REGISTRATION</a>
  <a href="{%url 'app1:vcourse'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">info</i>VIEW COURSES</a>
  <a href="{%url 'app1:allstu'%}" class="list-group-item list-group-item-action"><i class="material-icons"style="font-size:36;vertical-align:bottom;">info</i>VIEW STUDENTS</a>
    <a href="{%url 'timetable:create'%}" class="list-group-item list-group-item-action"><i class="material-icons"style="font-size:36;vertical-align:bottom;">alarm_add</i>SET TIMETABLE</a>
  <a href="{%url 'app1:addpay'%}" class="list-group-item list-group-item-action"><i class="material-icons"style="font-size:36;vertical-align:bottom;">payment</i>PAYMENT</a>
{%else%}
<title>HR</title>
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">HR</a>
   {%if form%}
    <div class="jumbotron">
        <img src="{% static 'images/loginicon.jpg'%}" style="margin-bottom:20px;margin-left:80px;vertical-align: middle;width: 50px;height: 50px;border-radius: 50%;">

    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input class="btn btn-success" type="submit" value="Submit">
    </form>
    </div>
  {%else%}
  <a href="{%url 'app1:newusr'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">how_to_reg</i>STUDENT REGISTRATION</a>
  <a href="{%url 'app1:vcourse'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">info</i>VIEW COURSES</a>
  <a href="{%url 'app1:allstu'%}" class="list-group-item list-group-item-action"><i class="material-icons"style="font-size:36;vertical-align:bottom;">info</i>VIEW STUDENTS</a>
    <a href="{%url 'timetable:create'%}" class="list-group-item list-group-item-action"><i class="material-icons"style="font-size:36;vertical-align:bottom;">alarm_add</i>SET TIMETABLE</a>
  <a href="{%url 'app1:addpay'%}" class="list-group-item list-group-item-action"><i class="material-icons"style="font-size:36;vertical-align:bottom;">payment</i>PAYMENT</a>
  {%endif%}
    {%endif%}
</div>
{%endblock%}

crm/app1/templates/app1/studentpg.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
{%load staticfiles%}
    {% block body_block%}
<title>STUDENT PAGE</title>
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">STUDENT</a>
    {%if form%}
    <div class="jumbotron">
        <img src="{% static 'images/loginicon.jpg'%}" style="margin-bottom:20px;margin-left:80px;vertical-align: middle;width: 50px;height: 50px;border-radius: 50%;">

    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input class="btn btn-success" type="submit" value="Submit">
    </form>
    </div>
    {%else%}
  <a href="{%url 'app1:stutb'%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">event</i>VIEW TIMETABLE</a>
  <a href="{%url 'dsp:report' stu.Name%}" class="list-group-item list-group-item-action"><i class="material-icons" style="font-size:36;vertical-align:bottom;">add_comment</i>DAILY SESSION REPORT</a>
    {%endif%}
</div>
{%endblock%}ml>

crm/app1/templates/app1/students.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
    {% block body_block%}
    <title>STUDENTS</title>
<div class="list-group">
    {%for i in rec%}
  <a href="{%url 'app1:details' i.Name%}" class="list-group-item list-group-item-action">{{i.Name}}</a>
    {%endfor%}
</div>
{%endblock%}