crm/crm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("app1.urls")),
    path("timetable", include("timetable.urls")),
    path("dailysessionreport", include("dsp.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
]

crm/dsp/urls.py
from django.urls import path
from dsp import views
app_name='dsp'
urlpatterns = [
    path("create/<str:pk>",views.DailyReport,name='report'),
    path("details/<int:pk>",views.Detail.as_view(),name='details'),
]

crm/dsp/models.py
from django.db import models
from datetime import datetime
from app1.models import Batch,Course,Trainer
# Create your models here.
class Status(models.Model):
    Status_Name=models.CharField(unique=True,max_length=200)
    def __str__(self):
        return self.Status_Name
class FeedbackOP(models.Model):
    options=models.CharField(unique=True,max_length=120)
    def __str__(self):
        return self.options
class SessionReport(models.Model):
    Student_Name=models.CharField(max_length=256)
    Trainer_Name=models.ForeignKey(Trainer,models.CASCADE)
    Topic=models.CharField(max_length=256)
    Status=models.ForeignKey(Status,on_delete=models.CASCADE)
    FeedBack=models.ForeignKey(FeedbackOP,on_delete=models.CASCADE)
    Date=models.DateField(default=datetime.now)
    def __str__(self):
        return str(self.Date)

crm/dsp/forms.py
from dsp.models import SessionReport
from django.forms import ModelForm
class SessionForm(ModelForm):
    class Meta:
        model=SessionReport
        fields='__all__'

crm/dsp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from dsp.models import SessionReport
from app1.models import Register
from dsp.forms import SessionForm
from django.views.generic import CreateView,TemplateView,DetailView
def DailyReport(request,pk):
    rec=SessionReport.objects.filter(Student_Name=pk)
    nm=Register.objects.get(Name=pk)
    form=SessionForm(initial={'Student_Name':nm.Name})
    dict={'form':form,'record':rec}
    if(request.method=='POST'):
        frm=SessionForm(request.POST)
        if frm.is_valid():
            frm.save(commit=True)
            return render(request,"dsp/report.html",dict)
    return render(request,"dsp/report.html",dict)

class Detail(DetailView):
    model = SessionReport
    fields='__all__'
    context_object_name = 'rec'
    template_name = 'dsp/details.html'

crm/dsp/templates/dsp/details.html
<!DOCTYPE html>
{%extends 'app1/base.html'%}
{%block body_block%}
    <title>Details</title>
<div class="jumbotron">
    <button type="button" class="btn btn-dark btn-lg" style="margin:5px;">{{rec.Student_Name}}</button>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">DATE</th>
      <th scope="col">TRAINER</th>
      <th scope="col">TOPIC</th>
      <th scope="col">STATUS</th>
      <th scope="col">FEEDBACK</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <td scope="col">{{rec}}</td>
      <td scope="col">{{rec.Trainer_Name}}</td>
      <td scope="col">{{rec.Topic}}</td>
      <td scope="col">{{rec.Status}}</td>
      <td scope="col">{{rec.FeedBack}}</td>
    </tr>
  </tbody>
</table>
    </div>
{%endblock%}

crm/dsp/templates/dsp/report.html
<!DOCTYPE html>
{%extends 'app1/base.html'%}
{%block body_block%}
    <title>Daily Report</title>
<div class="jumbotron">
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Submit" class="btn btn-success">
</form>
</div>
<div class="list-group" style="margin:10px;">
  <a href="#" class="list-group-item list-group-item-action active">
    Date
  </a>
    {%for rec in record%}
    <ul>
        <a href="{%url 'dsp:details' rec.id%}" class="list-group-item list-group-item-action">{{rec}}</a>
    </ul>
    {%endfor%}
</div>
{%endblock%}